// content/4-组件组合使用/2-Emit事件/react/App.jsx
import { useState } from "react";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
  const [happy, setHappy] = useState(true);

  function onAnswerNo() {
    setHappy(false);
  }

  function onAnswerYes() {
    setHappy(true);
  }

  return (
    <>
      <p>你快乐吗?</p>
      <AnswerButton onYes={onAnswerYes} onNo={onAnswerNo} />
      <p style={{ fontSize: 50 }}>{happy ? "😀" : "😥"}</p>
    </>
  );
}

// content/4-组件组合使用/2-Emit事件/solid/App.jsx
import { createSignal } from "solid-js";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
  const [happy, setHappy] = createSignal(true);

  function onAnswerNo() {
    setHappy(false);
  }

  function onAnswerYes() {
    setHappy(true);
  }

  return (
    <>
      <p>你快乐吗?</p>
      <AnswerButton onYes={onAnswerYes} onNo={onAnswerNo} />
      <p style={{ "font-size": "50px" }}>{happy() ? "😀" : "😥"}</p>
    </>
  );
}
