// content/2-templating/4-event-click/qwik/Counter.tsx
import { component$, useSignal, $ } from "@builder.io/qwik";

export const Counter = component$(() => {
  const count = useSignal(0);

  const incrementCount = $(() => {
    count.value++;
  });

  return (
    <>
      <p>计数器: {count.value}</p>
      <button onClick$={incrementCount}>Increment</button>
    </>
  );
});

// content/2-templating/4-event-click/angularRenaissance/counter.component.ts
import { Component, signal } from "@angular/core";

@Component({
  selector: "app-counter",
  template: `
    <p>计数器: {{ count() }}</p>
    <button (click)="incrementCount()">+1</button>
  `,
})
export class CounterComponent {
  count = signal(0);

  incrementCount() {
    this.count.update((count) => count + 1);
  }
}
