// content/6-表单输入/1-输入框/solid/InputHello.jsx
import { createSignal } from "solid-js";

export default function InputHello() {
  const [text, setText] = createSignal("这是一段示例文字");

  function handleChange(event) {
    setText(event.target.value);
  }

  return (
    <>
      <p>{text()}</p>
      <input value={text()} onInput={handleChange} />
    </>
  );
}

// content/6-表单输入/1-输入框/react/InputHello.jsx
import { useState } from "react";

export default function InputHello() {
  const [text, setText] = useState("这是一段示例文字");

  function handleChange(event) {
    setText(event.target.value);
  }

  return (
    <>
      <p>{text}</p>
      <input value={text} onChange={handleChange} />
    </>
  );
}
