// content/4-组件组合/2-向父组件emit事件/vue2/AnswerButton.vue
<script>
export default {
  methods: {
    clickYes() {
      this.$emit("yes");
    },
    clickNo() {
      this.$emit("no");
    },
  },
};
</script>

<template>
  <div>
    <button @click="clickYes">
      是的！
    </button>

    <button @click="clickNo">
      不是！
    </button>
  </div>
</template>

// content/4-组件组合/2-向父组件emit事件/lit/answer-button.js
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("answer-button")
export class AnswerButton extends LitElement {
  clickYes() {
    this.dispatchEvent(new Event("yes"));
  }

  clickNo() {
    this.dispatchEvent(new Event("no"));
  }

  render() {
    return html`
      <button @click=${this.clickYes}>是的！</button>
      <button @click=${this.clickNo}>不是！</button>
    `;
  }
}
