// content/4-组件组合/5-上下文/react/App.jsx
import { useState } from "react";
import UserProfile from "./UserProfile";
import { UserContext } from "./UserContext";

export default function App() {
  // 在实际项目，你会从接口获取用户数据
  const [user, setUser] = useState({
    id: 1,
    username: "abcdefg",
    email: "abcdefg@example.com",
  });

  function updateUsername(newUsername) {
    setUser((userData) => ({ ...userData, username: newUsername }));
  }

  return (
    <>
      <h1>欢迎回来, {user.username}</h1>
      <UserContext.Provider value={{ ...user, updateUsername }}>
        <UserProfile />
      </UserContext.Provider>
    </>
  );
}

// content/4-组件组合/5-上下文/svelte/App.svelte
<script>
  import { setContext } from "svelte";
  import UserProfile from "./UserProfile.svelte";
  import createUserStore from "./createUserStore.js";

  // 在实际项目，你会从接口获取用户数据
  const userStore = createUserStore({
    id: 1,
    username: "abcdefg",
    email: "abcdefg@example.com",
  });

  setContext("user", userStore);
</script>

<h1>欢迎回来, {$userStore.username}</h1>
<UserProfile />
