// content/4-组件组合/2-向父组件emit事件/vue2/AnswerButton.vue
<script>
export default {
  methods: {
    clickYes() {
      this.$emit("yes");
    },
    clickNo() {
      this.$emit("no");
    },
  },
};
</script>

<template>
  <div>
    <button @click="clickYes">
      是的！
    </button>

    <button @click="clickNo">
      不是！
    </button>
  </div>
</template>

// content/4-component-composition/2-emit-to-parent/angular/answer-button.component.ts
import { Component, Output, EventEmitter, NgModule } from "@angular/core";

@Component({
  selector: "app-answer-button",
  template: `
    <button (click)="yes.emit()">是的！</button>
    <button (click)="no.emit()">不是！</button>
  `,
})
export class AnswerButtonComponent {
  @Output() yes = new EventEmitter<void>();
  @Output() no = new EventEmitter<void>();
}

@NgModule({
  declarations: [AnswerButtonComponent],
  exports: [AnswerButtonComponent],
})
export class AnswerButtonModule {}
