// content/6-表单输入/3-单选框/qwik/PickPill.tsx
import { component$, useStore, $ } from "@builder.io/qwik";

const PickPill = component$(() => {
  const store = useStore({ picked: "red" });

  const handleChange = $((event: Event) => {
    store.picked = (event.target as HTMLInputElement).value;
  });

  return (
    <>
      <div>你选择了: {store.picked}</div>
      <input
        id="blue-pill"
        checked={store.picked === "blue"}
        type="radio"
        value="blue"
        onChange$={handleChange}
      />
      <label for="blue-pill">蓝色</label>

      <input
        id="red-pill"
        checked={store.picked === "red"}
        type="radio"
        value="red"
        onChange$={handleChange}
      />
      <label for="red-pill">红色</label>
    </>
  );
});

export default PickPill;

// content/6-表单输入/3-单选框/react/PickPill.jsx
import { useState } from "react";

export default function PickPill() {
  const [picked, setPicked] = useState("red");

  function handleChange(event) {
    setPicked(event.target.value);
  }

  return (
    <>
      <div>你选择了: {picked}</div>

      <input
        id="blue-pill"
        checked={picked === "blue"}
        type="radio"
        value="blue"
        onChange={handleChange}
      />
      <label htmlFor="blue-pill">蓝色</label>

      <input
        id="red-pill"
        checked={picked === "red"}
        type="radio"
        value="red"
        onChange={handleChange}
      />
      <label htmlFor="red-pill">红色</label>
    </>
  );
}
