// content/4-组件组合使用/5-context/react/UserProfile.jsx
import { useContext } from "react";
import { UserContext } from "./UserContext";

export default function UserProfile() {
  const { username, email, updateUsername } = useContext(UserContext);

  return (
    <div>
      <h2>My Profile</h2>
      <p>Username: {username}</p>
      <p>Email: {email}</p>
      <button onClick={() => updateUsername("李四")}>
        Update username to 李四
      </button>
    </div>
  );
}

// content/4-组件组合使用/5-context/vue3/UserProfile.vue
<script setup>
import { inject } from "vue";
const { user, updateUsername } = inject("user");
</script>

<template>
  <div>
    <h2>My Profile</h2>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <button @click="() => updateUsername('李四')">
      Update username to 李四
    </button>
  </div>
</template>
