// content/4-组件组合使用/5-context/svelte/UserProfile.svelte
<script>
  import { getContext } from "svelte";

  const userStore = getContext("user");
</script>

<div>
  <h2>My Profile</h2>
  <p>Username: {$userStore.username}</p>
  <p>Email: {$userStore.email}</p>
  <button on:click={() => userStore.updateUsername("李四")}>
    Update username to 李四
  </button>
</div>

// content/4-组件组合使用/5-context/vue3/UserProfile.vue
<script setup>
import { inject } from "vue";
const { user, updateUsername } = inject("user");
</script>

<template>
  <div>
    <h2>My Profile</h2>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <button @click="() => updateUsername('李四')">
      Update username to 李四
    </button>
  </div>
</template>
