// content/6-form-input/2-checkbox/react/IsAvailable.jsx
import { useState } from "react";

export default function IsAvailable() {
  const [isAvailable, setIsAvailable] = useState(false);

  function handleChange() {
    setIsAvailable(!isAvailable);
  }

  return (
    <>
      <input
        id="is-available"
        type="checkbox"
        checked={isAvailable}
        onChange={handleChange}
      />
      <label htmlFor="is-available">这是一个checkbox</label>
    </>
  );
}

// content/6-表单输入/2-复选框/qwik/IsAvailable.tsx
import { component$, useStore, $ } from "@builder.io/qwik";

const IsAvailable = component$(() => {
  const store = useStore({ isAvailable: false });

  const handleChange = $(() => {
    store.isAvailable = !store.isAvailable;
  });

  return (
    <>
      <input
        id="is-available"
        type="checkbox"
        checked={store.isAvailable}
        onChange$={handleChange}
      />
      <label for="is-available">这是一个checkbox</label>
    </>
  );
});

export default IsAvailable;
