// content/6-form-input/3-radio/vue3/PickPill.vue
<script setup>
import { ref } from "vue";

const picked = ref("red");
</script>

<template>
  <div>你选择了: {{ picked }}</div>

  <input id="blue-pill" v-model="picked" type="radio" value="blue" />
  <label for="blue-pill">蓝色</label>

  <input id="red-pill" v-model="picked" type="radio" value="red" />
  <label for="red-pill">红色</label>
</template>

// content/6-form-input/3-radio/qwik/PickPill.tsx
import { component$, useSignal } from "@builder.io/qwik";

const PickPill = component$(() => {
  const pickedColor = useSignal("red");

  return (
    <>
      <div>你选择了: {pickedColor.value}</div>
      <input
        id="blue-pill"
        type="radio"
        bind:value={pickedColor}
        checked={pickedColor.value === "blue"}
        value="blue"
      />
      <label for="blue-pill">蓝色</label>

      <input
        id="red-pill"
        type="radio"
        checked={pickedColor.value === "red"}
        bind:value={pickedColor}
        value="red"
      />
      <label for="red-pill">红色</label>
    </>
  );
});

export default PickPill;
