// content/7-web功能/2-fetch-data/react/App.jsx
import useFetchUsers from "./useFetchUsers";

export default function App() {
  const { isLoading, error, data: users } = useFetchUsers();

  return (
    <>
      {isLoading ? (
        <p>正在获取用户信息</p>
      ) : error ? (
        <p>获取用户信息出错</p>
      ) : (
        users && (
          <ul>
            {users.map((user) => (
              <li key={user.login.uuid}>
                <img src={user.picture.thumbnail} alt="user" />
                <p>
                  {user.name.first} {user.name.last}
                </p>
              </li>
            ))}
          </ul>
        )
      )}
    </>
  );
}

// content/7-web功能/2-fetch-data/svelte/App.svelte
<script>
  import useFetchUsers from "./useFetchUsers";

  const { isLoading, error, data: users } = useFetchUsers();
</script>

{#if $isLoading}
  <p>正在获取用户信息</p>
{:else if $error}
  <p>获取用户信息出错</p>
{:else if $users}
  <ul>
    {#each $users as user}
      <li>
        <img src={user.picture.thumbnail} alt="user" />
        <p>
          {user.name.first}
          {user.name.last}
        </p>
      </li>
    {/each}
  </ul>
{/if}
