// content/4-组件组合使用/2-Emit事件/svelte/App.svelte
<script>
  import AnswerButton from "./AnswerButton.svelte";

  let happy = true;

  function onAnswerNo() {
    happy = false;
  }

  function onAnswerYes() {
    happy = true;
  }
</script>

<p>你快乐吗?</p>
<AnswerButton on:yes={onAnswerYes} on:no={onAnswerNo} />
<p style="font-size: 50px;">{happy ? "😀" : "😥"}</p>

// content/4-组件组合使用/2-Emit事件/vue3/App.vue
<script setup>
import { ref } from "vue";
import AnswerButton from "./AnswerButton.vue";

let happy = ref(true);

function onAnswerNo() {
  happy.value = false;
}

function onAnswerYes() {
  happy.value = true;
}
</script>

<template>
  <p>你快乐吗?</p>
  <AnswerButton
    @yes="onAnswerYes"
    @no="onAnswerNo"
  />
  <p style="font-size: 50px">
    {{ happy ? "😀" : "😥" }}
  </p>
</template>
