// content/6-表单输入/3-单选框/react/PickPill.jsx
import { useState } from "react";

export default function PickPill() {
  const [picked, setPicked] = useState("red");

  function handleChange(event) {
    setPicked(event.target.value);
  }

  return (
    <>
      <div>你选择了: {picked}</div>

      <input
        id="blue-pill"
        checked={picked === "blue"}
        type="radio"
        value="blue"
        onChange={handleChange}
      />
      <label htmlFor="blue-pill">蓝色</label>

      <input
        id="red-pill"
        checked={picked === "red"}
        type="radio"
        value="red"
        onChange={handleChange}
      />
      <label htmlFor="red-pill">红色</label>
    </>
  );
}

// content/6-表单/3-单选/angular/pick-pill.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-pick-pill",
  template: `
    <div>你选择了: {{ picked }}</div>

    <input
      id="blue-pill"
      [checked]="picked === 'blue'"
      type="radio"
      value="blue"
      (change)="handleChange($event)"
    />
    <label for="blue-pill">蓝色</label>

    <input
      id="red-pill"
      [checked]="picked === 'red'"
      type="radio"
      value="red"
      (change)="handleChange($event)"
    />
    <label for="red-pill">红色</label>
  `,
})
export class PickPillComponent {
  picked = "red";

  handleChange(event) {
    this.picked = event.target.value;
  }
}
