// content/4-component-composition/5-context/solid/UserProfile.jsx
import { useContext } from "solid-js";

import { UserContext } from "./UserContext";

export default function UserProfile() {
  const [user, updateUsername] = useContext(UserContext);

  return (
    <div>
      <h2>我的简介</h2>
      <p>用户名: {user().username}</p>
      <p>邮箱: {user().email}</p>
      <button onClick={() => updateUsername("李四")}>
        更新用户名为 李四
      </button>
    </div>
  );
}

// content/4-组件组合/5-上下文/react/UserProfile.jsx
import { useContext } from "react";
import { UserContext } from "./UserContext";

export default function UserProfile() {
  const { username, email, updateUsername } = useContext(UserContext);

  return (
    <div>
      <h2>我的简介</h2>
      <p>用户名: {username}</p>
      <p>邮箱: {email}</p>
      <button onClick={() => updateUsername("李四")}>
        更新用户名为 李四
      </button>
    </div>
  );
}
