// content/6-form-input/2-checkbox/lit/is-available.js
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("is-available")
export class IsAvailable extends LitElement {
  @state()
  isAvailable = false;

  handleChange() {
    this.isAvailable = !this.isAvailable;
  }

  render() {
    return html`
      <input
        id="is-available"
        type="checkbox"
        ?checked=${this.isAvailable}
        @change=${this.handleChange}
      />
      <label for="is-available">这是一个checkbox</label>
    `;
  }
}

// content/6-表单/2-勾选框/angular/is-available.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-is-available",
  template: `
    <input
      id="is-available"
      type="checkbox"
      [checked]="isAvailable"
      (change)="handleChange()"
    />
    <label for="is-available">这是一个checkbox</label>
  `,
})
export class IsAvailableComponent {
  isAvailable = false;

  handleChange() {
    this.isAvailable = !this.isAvailable;
  }
}
