// content/4-组件组合使用/5-多层级组件通信/svelte/App.svelte
<script>
  import { setContext } from "svelte";
  import UserProfile from "./UserProfile.svelte";
  import createUserStore from "./createUserStore.js";

  // In a real app, you would fetch the user data from an API
  const userStore = createUserStore({
    id: 1,
    username: "abcdefg",
    email: "abcdefg@example.com",
  });

  setContext("user", userStore);
</script>

<h1>欢迎回来, {$userStore.username}</h1>
<UserProfile />

// content/4-组件组合使用/5-多层级组件通信/react/App.jsx
import { useState, createContext } from "react";
import UserProfile from "./UserProfile";

export const UserContext = createContext();

export default function App() {
  // In a real app, you would fetch the user data from an API
  const [user, setUser] = useState({
    id: 1,
    username: "abcdefg",
    email: "abcdefg@example.com",
  });

  function updateUsername(newUsername) {
    setUser((userData) => ({ ...userData, username: newUsername }));
  }

  return (
    <>
      <h1>欢迎回来, {user.username}</h1>
      <UserContext.Provider value={{ ...user, updateUsername }}>
        <UserProfile />
      </UserContext.Provider>
    </>
  );
}
