// content/4-组件组合使用/5-多层级组件通信/react/UserProfile.jsx
import { useContext } from "react";
import { UserContext } from "./UserContext";

export default function UserProfile() {
  const { username, email, updateUsername } = useContext(UserContext);

  return (
    <div>
      <h2>我的简介</h2>
      <p>用户名: {username}</p>
      <p>邮箱: {email}</p>
      <button onClick={() => updateUsername("李四")}>
        更新用户名为李四
      </button>
    </div>
  );
}

// content/4-组件组合使用/5-多层级组件通信/vue3/UserProfile.vue
<script setup>
import { inject } from "vue";
const { user, updateUsername } = inject("user");
</script>

<template>
  <div>
    <h2>我的简介</h2>
    <p>用户名: {{ user.username }}</p>
    <p>邮箱: {{ user.email }}</p>
    <button @click="() => updateUsername('李四')">
      更新用户名为李四
    </button>
  </div>
</template>
