// content/2-模板语法/6-条件渲染/vue3/TrafficLight.vue
<script setup>
import { ref, computed } from "vue";
const TRAFFIC_LIGHTS = ["红灯", "黄灯", "绿灯"];
const lightIndex = ref(0);

const light = computed(() => TRAFFIC_LIGHTS[lightIndex.value]);

function nextLight() {
  if (lightIndex.value + 1 > TRAFFIC_LIGHTS.length - 1) {
    lightIndex.value = 0;
  } else {
    lightIndex.value++;
  }
}
</script>

<template>
  <button @click="nextLight">
    下一个灯
  </button>
  <p>现在亮着的是: {{ light }}</p>
  <p>
    你应该
    <span v-if="light === '红灯'">停下</span>
    <span v-else-if="light === '黄灯'">慢行</span>
    <span v-else-if="light === '绿灯'">赶紧走</span>
  </p>
</template>

// content/2-templating/6-conditional/svelte4/TrafficLight.svelte
<script>
  const TRAFFIC_LIGHTS = ["红灯", "黄灯", "绿灯"];
  let lightIndex = 0;

  $: light = TRAFFIC_LIGHTS[lightIndex];

  function nextLight() {
    lightIndex = (lightIndex + 1) % TRAFFIC_LIGHTS.length;
  }
</script>

<button on:click={nextLight}>下一个灯</button>
<p>现在亮着的是: {light}</p>
<p>
  你应该
  {#if light === "红灯"}
    <span>停下</span>
  {:else if light === "黄灯"}
    <span>慢行</span>
  {:else if light === "绿灯"}
    <span>赶紧走</span>
  {/if}
</p>
