// content/4-component-composition/4-slot-fallback/svelte5/FunnyButton.svelte
<script>
  let { children } = $props();
</script>

<button
  style="background: rgba(0, 0, 0, 0.4); color: #fff; padding: 10px 20px; font-size: 30px; border: 2px solid #fff; margin: 8px; transform: scale(0.9); box-shadow: 4px 4px rgba(0, 0, 0, 0.4); transition: transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s; outline: 0;"
>
  {#if children}
    {@render children()}
  {:else}
    <span>默认slot内容</span>
  {/if}
</button>

// content/4-组件组合/4-slot插槽内容/solid/FunnyButton.jsx
export default function FunnyButton(props) {
  return (
    <button
      style={{
        background: "rgba(0, 0, 0, 0.4)",
        color: "#fff",
        padding: "10px 20px",
        "font-size": "30px",
        border: "2px solid #fff",
        margin: "8px",
        transform: "scale(0.9)",
        "box-shadow": "4px 4px rgba(0, 0, 0, 0.4)",
        transition: "transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s",
        outline: "0",
      }}
    >
      {props.children || <span>默认slot内容</span>}
    </button>
  );
}
