// content/4-组件组合/2-向父组件emit事件/vue2/AnswerButton.vue
<script>
export default {
  methods: {
    clickYes() {
      this.$emit("yes");
    },
    clickNo() {
      this.$emit("no");
    },
  },
};
</script>

<template>
  <div>
    <button @click="clickYes">
      是的！
    </button>

    <button @click="clickNo">
      不是！
    </button>
  </div>
</template>

// content/4-组件组合使用/2-Emit事件/angular/answer-button.component.ts
import { Component, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-answer-button",
  template: `
    <button (click)="yes.emit()">是的！</button>
    <button (click)="no.emit()">不是！</button>
  `,
})
export class AnswerButtonComponent {
  @Output() yes = new EventEmitter<void>();
  @Output() no = new EventEmitter<void>();
}
