// content/4-组件组合使用/1-props/vue2/UserProfile.vue
<script>
export default {
  props: {
    name: {
      type: String,
      required: true,
      default: "",
    },
    age: {
      type: Number,
      required: true,
      default: null,
    },
    favoriteColors: {
      type: Array,
      required: true,
      default: () => [],
    },
    isAvailable: {
      type: Boolean,
      required: true,
      default: false,
    },
  },
};
</script>

<template>
  <div>
    <p>我的名字是 {{ props.name }}!</p>
    <p>我的年龄是 {{ props.age }}!</p>
    <p>My favorite colors are {{ props.favoriteColors.join(", ") }}!</p>
    <p>我现在 {{ props.isAvailable ? '离职状态' : '在职' }}</p>
  </div>
</template>

// content/4-组件组合使用/1-props/lit/user-profile.js
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("user-profile")
export class UserProfile extends LitElement {
  @property()
  name = "";

  @property({ type: Number })
  age = null;

  @property({ type: Array })
  favouriteColors = [];

  @property({ type: Boolean })
  isAvailable = false;

  render() {
    return html`
      <p>我的名字是 ${this.name}</p>
      <p>我的年龄是 ${this.age}</p>
      <p>My favourite coloros are ${this.favouriteColors.join(", ")}</p>
      <p>我现在 ${this.isAvailable ? '离职状态' : '在职'}</p>
    `;
  }
}
