// content/4-组件组合使用/2-Emit事件/react/App.jsx
import { useState } from "react";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
  const [happy, setHappy] = useState(true);

  function onAnswerNo() {
    setHappy(false);
  }

  function onAnswerYes() {
    setHappy(true);
  }

  return (
    <>
      <p>你快乐吗?</p>
      <AnswerButton onYes={onAnswerYes} onNo={onAnswerNo} />
      <p style={{ fontSize: 50 }}>{happy ? "😀" : "😥"}</p>
    </>
  );
}

// content/4-组件组合使用/2-Emit事件/qwik/App.tsx
import { $, component$, useStore } from "@builder.io/qwik";
import AnswerButton from "./AnswerButton";

const App = component$(() => {
  const store = useStore({
    happy: true,
  });

  const onAnswerNo = $(() => {
    store.happy = false;
  });

  const onAnswerYes = $(() => {
    store.happy = true;
  });

  return (
    <>
      <p>你快乐吗?</p>
      <AnswerButton onYes$={onAnswerYes} onNo$={onAnswerNo} />
      <p style={{ fontSize: 50 }}>{store.happy ? "😀" : "😥"}</p>
    </>
  );
});

export default App;
